export const Images = {
      sample: {uri: 'https://d33wubrfki0l68.cloudfront.net/554c3b0e09cf167f0281fda839a5433f2040b349/ecfc9/img/header_logo.svg'},
      leaderboardIcon: require('../assets/images/rewarded_ads.png'),
      trash_1: require('../assets/images/trash.png'),
      trash_2: {uri: 'https://www.wric.com/wp-content/uploads/sites/74/2022/07/thumbnail_Image-2022-07-13T183843.797.jpg?w=1280'},
      trash_3: {uri: 'https://media.istockphoto.com/id/1125972087/photo/an-empty-glass-under-the-drink-lies-in-the-middle-of-the-street-pollution-concept-of-purity.jpg?s=612x612&w=0&k=20&c=2HFj05RS2bjdyBE3FDkf78Z-yb7wotTuYh9RkoRBOKQ='},
      challengesIcon: require('../assets/images/challenges.png'),
      sellScrapIcon: require('../assets/images/sellscrap.png'),
      greenCity: {uri: 'https://img.freepik.com/premium-vector/panama-city-skyscraper-view-cityscape-background_48369-5643.jpg'},
      profileEmoji_1: require('../assets/images/profileEmoji_1.png'),
      CO2cloud: require('../assets/images/CO2cloud.png'),
      giftIcon: require('../assets/images/giftButton.png'),
      carbonFootprint: {uri: 'https://media.istockphoto.com/id/472995805/video/carbon-footprint.jpg?s=640x640&k=20&c=ic3DA9fsWIPIHYDarSfUZCxHcszShLTu5-SaIAB5eus='},
      plasticFootprint: {uri: 'https://media.istockphoto.com/id/1303411090/vector/garbage-in-polluted-sea-ocean-water-nature-scenery-with-plastic-bottle-trash-waste.jpg?s=612x612&w=0&k=20&c=lXJunYk8xRi3SAslWcOui2H1VH6N5iYKaZ6KYfJv_8w='},
      captureButtonBorder: require('../assets/images/captureBorder.png'),
      litterPostedGif: require('../assets/images/animation_lkgfz5pn.json'),
      eventConfirmGif: require('../assets/images/animation_lkm93ov3.json'),
      rewardsGifJson: require('../assets/images/animation_lkrybg67.json'),
      rewardsGif: require('../assets/images/animation_lkryusah_small.gif'),
      coinIcon: require('../assets/images/coinicon.png'),
      leftLinearLine: require('../assets/images/leftlinelinear.png'),
      rightLinearLine: require('../assets/images/rightlinelinear.png'),
      sampleTshirt: {uri: 'https://assets.winni.in/product/primary/2023/2/82971.jpeg?dpr=1&w=500'},
      sampleShoe: {uri: 'https://hips.hearstapps.com/hmg-prod/images/best-shoes-for-nurses-1654635748.png'},
      sampleHoodie: {uri: 'https://www.splypromo.com/cdn/shop/products/4.png?v=1661753117'},
      inviteFrame: require('../assets/images/inviteframe.png'),
      timer: require('../assets/images/timer.png'),
      paperArt: require('../assets/images/paper_art.png'),
      unchecked: require('../assets/images/unchecked.png'),
      checked: require('../assets/images/checked.png'),
      uploadscreenframe: require('../assets/images/uploadscreenframe.png'),
      locationbottomimage: require('../assets/images/locationbottomimage.png'),
      animatedtruckleft: require('../assets/images/animatedtruckleft.png'),
      thumbsup_man: require('../assets/images/thumbsup_man.png'),
      sembwaselogo: require('../assets/images/sembwaselogo.png'),
      lb1st: require('../assets/images/lb1st.png'),
      lb2nd: require('../assets/images/lb2nd.png'),
      lb3rd: require('../assets/images/lb3rd.png'),
      lbcountbadge: require('../assets/images/lbcountbadge.png'),
      profileAvatar: {uri: 'https://www.w3schools.com/w3images/avatar2.png'},
      mygroupjoinimg: require('../assets/images/mygroupjoinimg.png'),
      like: require('../assets/images/like.png'),
      unlike: require('../assets/images/unlike.png'),
      expandContent: require('../assets/images/expand_content.png'),
      connectionoff: require('../assets/images/connectionoff.png'),
      erroroccured_1: require('../assets/images/erroroccured_1.png'),
      erroroccured_2: require('../assets/images/erroroccured_2.png'),
      locationerror: require('../assets/images/locationerror.png'),
}